# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

r1=  Room.create( number: '2313', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r2=  Room.create( number: '2314', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r3=  Room.create( number: '2315', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r4=  Room.create( number: '2323', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r5=  Room.create( number: '2324', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r6=  Room.create( number: '2325', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r7=  Room.create( number: '2327', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r8=  Room.create( number: '3217', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r9=  Room.create( number: '3218', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r10=  Room.create( number: '3219', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r11=  Room.create( number: '3220', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r12=  Room.create( number: '3313', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r13=  Room.create( number: '3314', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r14=  Room.create( number: '3315', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r15=  Room.create( number: '3316', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r16=  Room.create( number: '4514', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r17=  Room.create( number: '4515', size: '4 Chairs (Small)', building: 'James B. Hunt Jr. Library')
r18=  Room.create( number: '1132', size: '4 Chairs (Small)', building: 'D. H. Hill Library')
r19=  Room.create( number: '1133', size: '4 Chairs (Small)', building: 'D. H. Hill Library')
r20=  Room.create( number: '2305', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r21=  Room.create( number: '2307', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r22=  Room.create( number: '2309', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r23=  Room.create( number: '2312', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r24=  Room.create( number: '2322', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r25=  Room.create( number: '2326', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r26=  Room.create( number: '2328', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r27=  Room.create( number: '3305', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r28=  Room.create( number: '3307', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r29=  Room.create( number: '3309', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r30=  Room.create( number: '3312', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r31=  Room.create( number: '4510', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r32=  Room.create( number: '4511', size: '6 Chairs (Medium)', building: 'James B. Hunt Jr. Library')
r33=  Room.create( number: '4419', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r34=  Room.create( number: '4430', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r35=  Room.create( number: '5419', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r36=  Room.create( number: '5430', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r37=  Room.create( number: '6406', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r38=  Room.create( number: '6419', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r39=  Room.create( number: '7406', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r40=  Room.create( number: '7419', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r41=  Room.create( number: '8406', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r42=  Room.create( number: '8419', size: '6 Chairs (Medium)', building: 'D. H. Hill Library')
r43=  Room.create( number: '3212', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r44=  Room.create( number: '3213', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r45=  Room.create( number: '3214', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r46=  Room.create( number: '3208', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r47=  Room.create( number: '3209', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r48=  Room.create( number: '4411', size: '8 Chairs (Large)', building: 'James B. Hunt Jr. Library')
r49=  Room.create( number: '2419', size: '8 Chairs (Large)', building: 'D. H. Hill Library')

u1= User.create( name: 'Prathamesh', email: 'prathamesh@gmail.com', password: 'user_password', role: 'user')
u2= User.create( name: 'Shankar', email: 'shankar@gmail.com', password: 'user_password', role: 'user')
u3= User.create( name: 'Vivek', email: 'vivek@gmail.com', password: 'user_password', role: 'user')
u4= User.create( name: 'SuperAdmin', email: 'sadmin@ncsu.edu', password: 'adminADMIN', role: 'sadmin')
u5= User.create( name: 'Admin', email: 'admin@ncsu.edu', password: 'adminADMIN', role: 'admin')


rs1= Reservation.create( booking_date: '2016-09-28', start_time: '17', end_time: '18', status: 'booked',user_id: u1.id,room_id: r1.id)
rs2= Reservation.create( booking_date: '2016-09-28', start_time: '1', end_time: '4', status: 'booked',user_id: u1.id,room_id: r2.id)
rs3= Reservation.create( booking_date: '2016-09-29', start_time: '17', end_time: '18', status: 'booked',user_id: u1.id,room_id: r3.id)
rs4= Reservation.create( booking_date: '2016-09-29', start_time: '0', end_time: '2', status: 'booked',user_id: u1.id,room_id: r4.id)